name = "elysium_bios.img"
protective-mbr = true
bootsector = "x86_64-bios.bin"

[[partitions]]
type = "file"
name = "Tartarus"
gpt-type = "54524154-5241-5355-424F-4F5450415254"
file = "tartarus.sys"

[[partitions]]
type = "fs"
gpt-type = "454C5953-4955-4D52-4F4F-545041525458"
fs-type = "fat32"
size = 64
files = ["image_root"]
